version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      GET_HOSTS_FROM: dns
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    container_name: cache
    expose:
      - 6379    
