version: '3'

services:
  app: 
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: on-failure
    depends_on: 
      - redis
      - db
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: docker-nginx.yml
    links: 
      - app:api.app
      - app:web.app
      - app:channel.app
    ports:
      - "80:80"
      - "443:443"
      depends_on: 
      - app
    networks:
      - backend
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./public/views:/var/www/html
  #   image: nginx:latest
  #   links: 
  #     - app:api.app
  #     - app:web.app
  #     - app:channel.app
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on: 
  #     - app
  #   networks:
  #     - backend
  #   volumes:
  #     - ./nginx/:/etc/nginx/conf.d/
  #     - ./public/views:/var/www/html
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - ./dhparam:/etc/ssl/certs
   
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - ./public/views:/var/www/html
  #   depends_on:
  #     - nginx
  #   command: certonly --webroot --webroot-path=/var/www/html --email intouch.opec@gmail.com --agree-tos --no-eff-email --force-renewal -d channel4.triple-t.cc 
    
  db:
    image: postgres:11.3
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todos
    networks:
      - backend

  redis:
    image: redis
    restart: always
    container_name: cache
    hostname: cache
    ports:
      - 6379:6379
    networks:
      - backend

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - backend
    links: 
      - db:db
    restart: unless-stopped

volumes:
  certbot-etc:
  certbot-var:

networks:
  backend:
    driver: bridge 
