version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=web.triple-t.cc
      - LETSENCRYPT_HOST=web.triple-t.cc
      - API_HOST=api.triple-t.cc
      - CHANNEL_HOST=channel.triple-t.cc

      