# default false
release_mode = false

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

# REDIS,FILE,COOKIE(COOKIE Default)
session_store = "REDIS"

# REDIS,MEMCACHED,IN_MEMORY(IN_MEMORY Default)
cache_store = "REDIS"

[app]
name = "Echo Web"
version = "0.0.1"

[server]
graceful = true
addr = ":8080"

# Domains
domain_api = "api.localhost"
domain_web = "web.localhost"
domain_socket = "socket.localhost"
domain_line_channel = "6bbfdf22.ngrok.io"
domain_static = "localhost"

[static]
# BINDATA,FILE(FILE Default)
type = "BINDATA"

[tmpl]
# PONGO2,TEMPLATE(TEMPLATE Default)
type = "PONGO2"
# BINDATA,FILE(FILE Default)
data = "BINDATA"
# PONGO2(template/pongo2),TEMPLATE(template)
dir = "template/pongo2"
# .html,.tpl
suffix = ".html"

[database]
name = "dev"
user_name = "postgres-dev"
pwd  = "password"
host = "127.0.0.1"
port = "5432"

[redis]
server = "cache:6379"
pwd = "password"

[memcached]
server = "127.0.0.1:11211"

[opentracing]
disable = false

# "jaeger" "appdash" or "elastic"
type = "elastic"

# jaeger or elastic serviceName
service_name = "echo-web"

# jaeger-agent 127.0.0.1:6831
# appdash localhost:8700
address = "127.0.0.1:6831"

[metrics]
disable = true
freq_sec = 10
address = "127.0.0.1:2003"  # Graphite
